### ISSUE TITLE
python3 encode error

### ISSUE THREAD

**Issue by mslacken** [aplanas/obsgit#11]
When running an ``obsgit export`` I am getting on openSUSE Leap 15.2 (python 3.6.10) followiing error:
Traceback (most recent call last):
  File "/usr/bin/obsgit", line 1259, in <module>
    loop.run_until_complete(args.func(args, config))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/usr/bin/obsgit", line 1022, in export
    git.create()
  File "/usr/bin/obsgit", line 270, in create
    pygit2.init_repository(self.path)
  File "/usr/lib64/python3.6/site-packages/pygit2/__init__.py", line 150, in init_repository
    err = C.git_repository_init_ext(crepository, to_bytes(path), options)
  File "/usr/lib64/python3.6/site-packages/pygit2/py3.py", line 42, in to_bytes
    return s.encode(encoding, errors)
AttributeError: 'PosixPath' object has no attribute 'encode'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fc4011ec198>

**Comment by aplanas** [comment]
seems a bug in pygit2, what are you exporting?

**Comment by mslacken** [comment]
I tried following command:
``obsgit export home:mslacken:ml ml-git``

**Comment by aplanas** [comment]
indeed, this is using a very old pygit2 that contains py2.py and py3.py compatibility libraries that are not there anymore since https://github.com/libgit2/pygit2/commit/85ebc957de55f6fe7dd382392b6846c592692910

I do no want to debug the old pygit2, so use a venv for now:

```
python3 -m venv venv
source venv/bin/activate
pip install asyncio pygit2
```

I managed to export the ml project. You will have several timeouts when OBS decides not to answer.

This is something that I should think about too, if is OK to retry or not after a server error. Some time ago this code was in obsgit, but to simplify I decided to drop it and let it fail. For big files like the one in ml this can be a problem.

Because I am not going to fix pygit2 for now, let me close this issue. We can open a new one for what to do when OBS time out.

Thanks!!

**Comment by aplanas** [comment]
Oh. The TO is easy to workaround. Just try again the export, obsgit knows how to continue.

**Comment by mslacken** [comment]
Unfortunately on Leap 15.2 I can't update pygit2 via virtual environment as there is a version mismatch
```
src/types.h:36:2: error: #error You need a compatible libgit2 version (1.0.x)
     #error You need a compatible libgit2 version (1.0.x)
```

**Comment by aplanas** [comment]
> Unfortunately on Leap 15.2 I can't update pygit2 via virtual environment as there is a version mismatch
> 
> ```
> src/types.h:36:2: error: #error You need a compatible libgit2 version (1.0.x)
>      #error You need a compatible libgit2 version (1.0.x)
> ```

Ouch. Lets reopen this then until we figure this out.

**Comment by aplanas** [comment]
Should be fixed by https://github.com/aplanas/obsgit/commit/39e943db983372e09933afd366a5b01e15dc4f9c
(credits to @bmwiedemann)
