### ISSUE TITLE
Import/export ignores linkpac

### ISSUE THREAD

**Issue by heliocastro** [aplanas/obsgit#14]
Current status of export/import project ignores if a package is a link instead of a real package.
So, as an example, kernel package officially is a link to kernel-source package.
The result after imported will be two packages, making any change in one of the sides inconsistent.

A possible solution for future is add a special command file on the exported source on what to do and how to react to specific package ( and source if involved ) when it is imported

Something like for each package a config file called package.cfg taht represents the file, or even
And inside:
packageType = link
linkTo = <some_other_package>

Would be easy if this info could be revovered by package meta or some other way thiough

**Comment by aplanas** [comment]
> Current status of export/import project ignores if a package is a link instead of a real package.
> So, as an example, kernel package officially is a link to kernel-source package.
> The result after imported will be two packages, making any change in one of the sides inconsistent.

This part is documented (from README.md):

```
# What to do when obsgit read a linked package:
# - always: always expand the _link, downloading the expanded source
# - never: never expand, download only the _link file. If link is
#     pointing to a different project, generate an error for this package
# - auto: expand the link only if point to a different project
link = never
```

The default value is "never", because is the correct one for the original use case. For example, in the kernel package only one will have the assets and the rest will have the _link, so there will be no inconsistency during the import (as will be a link too).

If you see that the export is a _link, and the import is a non-linked package, something is wrong in the build server configuration, as obsgit decides the link expansion during the export stage.

I will close this issue, unless I am misreading something.

**Comment by aplanas** [comment]
@heliocastro ping here. Did you checked that the linkpac are indeed _link under git?

**Comment by heliocastro** [comment]
Not sure if i understood, but i tried to export my local build.opensuse project, home:heliochissini:carwos that have several links, and not saw any link description on it.
You can export this project as well, since is small enough to see. More easily, you can export the package kernel-rt
I tried with both link=auto and link=true on the export

**Comment by aplanas** [comment]
> home:heliochissini:carwos

I see the problem. You have a link to an external kernel-source-rt, to coolo's package. In this case "auto" and "True" have the same meaning: expand the link.

#### Test 1: `link = never` (default)
```bash
$ ./obsgit/obsgit export -p kernel-rt home:heliochissini:carwos carwos
Initialized the git repository
Git LFS extension enabled in the repository
home:heliochissini:carwos/kernel-rt ...

$ ls carwos/packages/kernel-rt/
_link
```

This works because kernel-rt is a link to kernel-source-rt in your home project, but if I try this:

```bash
$ ./obsgit/obsgit export -p kernel-source-rt home:heliochissini:carwos carwos
Initialized the git repository
Git LFS extension enabled in the repository
home:heliochissini:carwos/kernel-source-rt ...
ERROR: Link home:heliochissini:carwos/kernel-source-rt pointing outside (home:coolo:carwos)
```

You have an error message. You state that the links will never be expanded but kernel-source-rt is a link to a package living outside your project.

`link = never` is the default because is the right thing for carwos, for example. You aim to a self contained project, where all the links are local, never pointing to something outside.

#### Test 2: `link = auto`

I changed the config file to set the link to `auto` expand. This means that all the link that are local will not be expanded, but if the link is to an external project, it will expand it.

```bash
$ rm -fr carwors

$ ./obsgit/obsgit export -p kernel-rt home:heliochissini:carwos carwos
Initialized the git repository
Git LFS extension enabled in the repository
home:heliochissini:carwos/kernel-rt ...

$ ls carwos/packages/kernel-rt/
_link

$ ./obsgit/obsgit export -p kernel-source-rt home:heliochissini:carwos carwos
Initialized the git repository
Git LFS extension enabled in the repository
home:heliochissini:carwos/kernel-source-rt ...

$ ls carwos/packages/kernel-source-rt/
apply-patches                 kernel-rt.changes         package-descriptions ...
```

As expected the first link is not expanded and the second one works, but is expanded downloading the assets from coolo's project, as the OBS project is not self-contained.

#### Test 3: `link = always`

This will expand both links, the local kernel-rt  and the external kernel-source-rt (check that yourself to validate this)

I guess that you somehow want the "auto" behavior, but I recommend to set the OBS project in a way that there are no external links.
